<?php

namespace ContainerDlhYinS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QP0WziAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qP0WziA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qP0WziA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookRepository' => ['privates', '.errored.iK2c.KK', NULL, 'Cannot determine controller argument for "App\\Controller\\ApiController::getBookByIsbn()": the $bookRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\BookRepository". Did you forget to add a use statement?'],
        ], [
            'bookRepository' => '?',
        ]);
    }
}
