<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDNHp8fj\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDNHp8fj/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDNHp8fj.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDNHp8fj\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerDNHp8fj\App_KernelTestDebugContainer([
    'container.build_hash' => 'DNHp8fj',
    'container.build_id' => '1f1fbc34',
    'container.build_time' => 1690601968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDNHp8fj');
