<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.62bcf186.js',
                'build/app.9e81bd06.js',
            ],
            'css' => [
                'build/app.845921e4.css',
            ],
        ],
    ],
],

]];
